package service

const (
	errorConnectToGRPCServer            = "connect to grpc server failed"
	errorExeVActiveSet                  = "exe if request is V or active from redis set failed"
	errorPublishVUserVideo              = "publish v user video information to redis failed"
	errorPublishActiveUserVideo         = "publish active user video information to redis failed"
	errorPushUserInfoList               = "push user information to redis list failed"
	errorCreateVideo                    = "create video failed"
	errorDeleteVideo                    = "delete video failed"
	errorIncrUserVideoCount             = "incr user video count failed"
	errorSubUserVideoCount              = "sub user video count failed"
	errorGetUserVideoCount              = "get user video count failed"
	errorAddUserVideoCountSet           = "add user video count set failed"
	errorGetVVideoInfo                  = "get v video information from redis failed"
	errorGetActiveVideoInfo             = "get active video information from redis failed"
	errorJsonMarshal                    = "json marshal failed"
	errorGetVideoInfo                   = "get video information failed"
	errorGetFavoriteCount               = "get favorite count and judge isFavorite failed"
	errorGetCommentCount                = "get comment count failed"
	errorGetUserInfo                    = "get user information failed"
	errorJudgeVideoAuthor               = "judge video author failed"
	errorGetVideoByVideoId              = "get video information by video id failed"
	errorGetVVideoInfoByVideoId         = "get v video information by video id failed"
	errorGetActiveVideoInfoByVideoId    = "get active video information by video id failed"
	errorPushVFavoriteVideoInfo         = "push v favorite video information failed"
	errorPushActiveFavoriteVideoInfo    = "push active favorite video information failed"
	errorGetVFavoriteVideoInfo          = "get v favorite video information failed"
	errorGetActiveFavoriteVideoInfo     = "get active favorite video information failed"
	errorDeleteVFavoriteVideoInfo       = "delete v favorite video information failed"
	errorDeleteActiveFavoriteVideoInfo  = "delete active favorite video information failed"
	errorGetVideoListByVideoId          = "get video list by video id failed"
	errorGetVideoInfoZSet               = "get video information zSet failed"
	errorJsonUnMarshal                  = "json unmarshal failed"
	errorGetVideoListByCreateTime       = "get video list by create time failed"
	errorGetUserFavoriteVideoIdList     = "get user favorite video id list failed"
	errorPushVActiveBasicInfoInit       = "push v or active basic info init failed"
	errorGetUserListFavoriteVideoIdList = "get user list favorite video id list failed"
	errorJudgeFeedIsFirst               = "judge feed is first failed"
	errorDeleteActiveVideoInfo          = "delete active video information failed"
	errorGetUserPublishVideoCountList   = "get user publish video count list failed"
	errorGetUserPublishVideoCount       = "get user publish video count failed"
	errorDeleteVUserVideo               = "delete v user video failed"
	errorDeleteActiveUserVideo          = "delete active user video failed"
	errorRpcInput                       = "rpc input failed"
	errorExecuteWorkflow                = "result of workflow.Execute is"
	errorRegisterWorkflow               = "workflow register failed"
)
