// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: video/request/request.proto

package request

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DouyinFeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LatestTime  int64 `protobuf:"varint,1,opt,name=latest_time,json=latestTime,proto3" json:"latest_time,omitempty"`
	LoginUserId int64 `protobuf:"varint,2,opt,name=login_user_id,json=loginUserId,proto3" json:"login_user_id,omitempty"`
}

func (x *DouyinFeedRequest) Reset() {
	*x = DouyinFeedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_request_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinFeedRequest) ProtoMessage() {}

func (x *DouyinFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_request_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinFeedRequest.ProtoReflect.Descriptor instead.
func (*DouyinFeedRequest) Descriptor() ([]byte, []int) {
	return file_video_request_request_proto_rawDescGZIP(), []int{0}
}

func (x *DouyinFeedRequest) GetLatestTime() int64 {
	if x != nil {
		return x.LatestTime
	}
	return 0
}

func (x *DouyinFeedRequest) GetLoginUserId() int64 {
	if x != nil {
		return x.LoginUserId
	}
	return 0
}

type DouyinPublishActionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoUrl string `protobuf:"bytes,1,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	CoverUrl string `protobuf:"bytes,2,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Title    string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	UserId   int64  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DouyinPublishActionRequest) Reset() {
	*x = DouyinPublishActionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_request_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinPublishActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinPublishActionRequest) ProtoMessage() {}

func (x *DouyinPublishActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_request_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinPublishActionRequest.ProtoReflect.Descriptor instead.
func (*DouyinPublishActionRequest) Descriptor() ([]byte, []int) {
	return file_video_request_request_proto_rawDescGZIP(), []int{1}
}

func (x *DouyinPublishActionRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *DouyinPublishActionRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *DouyinPublishActionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DouyinPublishActionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DouyinPublishListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LoginId int64 `protobuf:"varint,2,opt,name=login_id,json=loginId,proto3" json:"login_id,omitempty"`
}

func (x *DouyinPublishListRequest) Reset() {
	*x = DouyinPublishListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_request_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinPublishListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinPublishListRequest) ProtoMessage() {}

func (x *DouyinPublishListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_request_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinPublishListRequest.ProtoReflect.Descriptor instead.
func (*DouyinPublishListRequest) Descriptor() ([]byte, []int) {
	return file_video_request_request_proto_rawDescGZIP(), []int{2}
}

func (x *DouyinPublishListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DouyinPublishListRequest) GetLoginId() int64 {
	if x != nil {
		return x.LoginId
	}
	return 0
}

type DouyinJudgeVideoAuthorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId int64 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
}

func (x *DouyinJudgeVideoAuthorRequest) Reset() {
	*x = DouyinJudgeVideoAuthorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_request_request_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinJudgeVideoAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinJudgeVideoAuthorRequest) ProtoMessage() {}

func (x *DouyinJudgeVideoAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_request_request_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinJudgeVideoAuthorRequest.ProtoReflect.Descriptor instead.
func (*DouyinJudgeVideoAuthorRequest) Descriptor() ([]byte, []int) {
	return file_video_request_request_proto_rawDescGZIP(), []int{3}
}

func (x *DouyinJudgeVideoAuthorRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type DouyinPushVActiveFavoriteVideoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId           int64 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	IsV               bool  `protobuf:"varint,2,opt,name=is_v,json=isV,proto3" json:"is_v,omitempty"`
	IsActive          bool  `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	LoginUserIsV      bool  `protobuf:"varint,4,opt,name=login_user_is_v,json=loginUserIsV,proto3" json:"login_user_is_v,omitempty"`
	LoginUserIsActive bool  `protobuf:"varint,5,opt,name=login_user_is_active,json=loginUserIsActive,proto3" json:"login_user_is_active,omitempty"`
	LoginUserId       int64 `protobuf:"varint,6,opt,name=login_user_id,json=loginUserId,proto3" json:"login_user_id,omitempty"`
	AuthorId          int64 `protobuf:"varint,7,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
}

func (x *DouyinPushVActiveFavoriteVideoRequest) Reset() {
	*x = DouyinPushVActiveFavoriteVideoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_request_request_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinPushVActiveFavoriteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinPushVActiveFavoriteVideoRequest) ProtoMessage() {}

func (x *DouyinPushVActiveFavoriteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_request_request_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinPushVActiveFavoriteVideoRequest.ProtoReflect.Descriptor instead.
func (*DouyinPushVActiveFavoriteVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_request_request_proto_rawDescGZIP(), []int{4}
}

func (x *DouyinPushVActiveFavoriteVideoRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *DouyinPushVActiveFavoriteVideoRequest) GetIsV() bool {
	if x != nil {
		return x.IsV
	}
	return false
}

func (x *DouyinPushVActiveFavoriteVideoRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *DouyinPushVActiveFavoriteVideoRequest) GetLoginUserIsV() bool {
	if x != nil {
		return x.LoginUserIsV
	}
	return false
}

func (x *DouyinPushVActiveFavoriteVideoRequest) GetLoginUserIsActive() bool {
	if x != nil {
		return x.LoginUserIsActive
	}
	return false
}

func (x *DouyinPushVActiveFavoriteVideoRequest) GetLoginUserId() int64 {
	if x != nil {
		return x.LoginUserId
	}
	return 0
}

func (x *DouyinPushVActiveFavoriteVideoRequest) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

type DouyinDeleteVActiveFavoriteVideoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId           int64 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UserId            int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LoginUserIsV      bool  `protobuf:"varint,4,opt,name=login_user_is_v,json=loginUserIsV,proto3" json:"login_user_is_v,omitempty"`
	LoginUserIsActive bool  `protobuf:"varint,5,opt,name=login_user_is_active,json=loginUserIsActive,proto3" json:"login_user_is_active,omitempty"`
}

func (x *DouyinDeleteVActiveFavoriteVideoRequest) Reset() {
	*x = DouyinDeleteVActiveFavoriteVideoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_request_request_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinDeleteVActiveFavoriteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinDeleteVActiveFavoriteVideoRequest) ProtoMessage() {}

func (x *DouyinDeleteVActiveFavoriteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_request_request_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinDeleteVActiveFavoriteVideoRequest.ProtoReflect.Descriptor instead.
func (*DouyinDeleteVActiveFavoriteVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_request_request_proto_rawDescGZIP(), []int{5}
}

func (x *DouyinDeleteVActiveFavoriteVideoRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *DouyinDeleteVActiveFavoriteVideoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DouyinDeleteVActiveFavoriteVideoRequest) GetLoginUserIsV() bool {
	if x != nil {
		return x.LoginUserIsV
	}
	return false
}

func (x *DouyinDeleteVActiveFavoriteVideoRequest) GetLoginUserIsActive() bool {
	if x != nil {
		return x.LoginUserIsActive
	}
	return false
}

type DouyinGetVActiveFavoriteVideoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsV      bool  `protobuf:"varint,4,opt,name=is_v,json=isV,proto3" json:"is_v,omitempty"`
	IsActive bool  `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (x *DouyinGetVActiveFavoriteVideoRequest) Reset() {
	*x = DouyinGetVActiveFavoriteVideoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_request_request_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinGetVActiveFavoriteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinGetVActiveFavoriteVideoRequest) ProtoMessage() {}

func (x *DouyinGetVActiveFavoriteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_request_request_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinGetVActiveFavoriteVideoRequest.ProtoReflect.Descriptor instead.
func (*DouyinGetVActiveFavoriteVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_request_request_proto_rawDescGZIP(), []int{6}
}

func (x *DouyinGetVActiveFavoriteVideoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DouyinGetVActiveFavoriteVideoRequest) GetIsV() bool {
	if x != nil {
		return x.IsV
	}
	return false
}

func (x *DouyinGetVActiveFavoriteVideoRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type DouyinGetVideoListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId []int64 `protobuf:"varint,1,rep,packed,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
}

func (x *DouyinGetVideoListRequest) Reset() {
	*x = DouyinGetVideoListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_request_request_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinGetVideoListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinGetVideoListRequest) ProtoMessage() {}

func (x *DouyinGetVideoListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_request_request_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinGetVideoListRequest.ProtoReflect.Descriptor instead.
func (*DouyinGetVideoListRequest) Descriptor() ([]byte, []int) {
	return file_video_request_request_proto_rawDescGZIP(), []int{7}
}

func (x *DouyinGetVideoListRequest) GetVideoId() []int64 {
	if x != nil {
		return x.VideoId
	}
	return nil
}

type Simple_Video struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId   int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlayUrl  string `protobuf:"bytes,3,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`
	CoverUrl string `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Title    string `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *Simple_Video) Reset() {
	*x = Simple_Video{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_request_request_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Simple_Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Simple_Video) ProtoMessage() {}

func (x *Simple_Video) ProtoReflect() protoreflect.Message {
	mi := &file_video_request_request_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Simple_Video.ProtoReflect.Descriptor instead.
func (*Simple_Video) Descriptor() ([]byte, []int) {
	return file_video_request_request_proto_rawDescGZIP(), []int{8}
}

func (x *Simple_Video) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Simple_Video) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Simple_Video) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *Simple_Video) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Simple_Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type DouyinPushVInfoInitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsActive bool  `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (x *DouyinPushVInfoInitRequest) Reset() {
	*x = DouyinPushVInfoInitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_request_request_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinPushVInfoInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinPushVInfoInitRequest) ProtoMessage() {}

func (x *DouyinPushVInfoInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_request_request_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinPushVInfoInitRequest.ProtoReflect.Descriptor instead.
func (*DouyinPushVInfoInitRequest) Descriptor() ([]byte, []int) {
	return file_video_request_request_proto_rawDescGZIP(), []int{9}
}

func (x *DouyinPushVInfoInitRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DouyinPushVInfoInitRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type DouyinPushActiveInfoInitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId []int64 `protobuf:"varint,1,rep,packed,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DouyinPushActiveInfoInitRequest) Reset() {
	*x = DouyinPushActiveInfoInitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_request_request_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinPushActiveInfoInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinPushActiveInfoInitRequest) ProtoMessage() {}

func (x *DouyinPushActiveInfoInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_request_request_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinPushActiveInfoInitRequest.ProtoReflect.Descriptor instead.
func (*DouyinPushActiveInfoInitRequest) Descriptor() ([]byte, []int) {
	return file_video_request_request_proto_rawDescGZIP(), []int{10}
}

func (x *DouyinPushActiveInfoInitRequest) GetUserId() []int64 {
	if x != nil {
		return x.UserId
	}
	return nil
}

type DouyinGetUserPublishVideoCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *DouyinGetUserPublishVideoCountRequest) Reset() {
	*x = DouyinGetUserPublishVideoCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_request_request_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinGetUserPublishVideoCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinGetUserPublishVideoCountRequest) ProtoMessage() {}

func (x *DouyinGetUserPublishVideoCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_request_request_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinGetUserPublishVideoCountRequest.ProtoReflect.Descriptor instead.
func (*DouyinGetUserPublishVideoCountRequest) Descriptor() ([]byte, []int) {
	return file_video_request_request_proto_rawDescGZIP(), []int{11}
}

func (x *DouyinGetUserPublishVideoCountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DouyinGetUserPublishVideoCountListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId []int64 `protobuf:"varint,1,rep,packed,name=userId,proto3" json:"userId,omitempty"`
}

func (x *DouyinGetUserPublishVideoCountListRequest) Reset() {
	*x = DouyinGetUserPublishVideoCountListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_request_request_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinGetUserPublishVideoCountListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinGetUserPublishVideoCountListRequest) ProtoMessage() {}

func (x *DouyinGetUserPublishVideoCountListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_request_request_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinGetUserPublishVideoCountListRequest.ProtoReflect.Descriptor instead.
func (*DouyinGetUserPublishVideoCountListRequest) Descriptor() ([]byte, []int) {
	return file_video_request_request_proto_rawDescGZIP(), []int{12}
}

func (x *DouyinGetUserPublishVideoCountListRequest) GetUserId() []int64 {
	if x != nil {
		return x.UserId
	}
	return nil
}

var File_video_request_request_proto protoreflect.FileDescriptor

var file_video_request_request_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5a, 0x0a, 0x13, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e,
	0x5f, 0x66, 0x65, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x22,
	0x0a, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x88, 0x01, 0x0a, 0x1d, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x72,
	0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x51, 0x0a,
	0x1b, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x64,
	0x22, 0x3e, 0x0a, 0x21, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f, 0x6a, 0x75, 0x64, 0x67, 0x65,
	0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64,
	0x22, 0x91, 0x02, 0x0a, 0x2b, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f, 0x70, 0x75, 0x73, 0x68,
	0x5f, 0x76, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69,
	0x74, 0x65, 0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x12, 0x11, 0x0a, 0x04, 0x69,
	0x73, 0x5f, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x69, 0x73, 0x56, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x25, 0x0a, 0x0f, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x73, 0x5f, 0x76, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x73, 0x56, 0x12, 0x2f, 0x0a, 0x14, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x11, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x73, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x49, 0x64, 0x22, 0xbb, 0x01, 0x0a, 0x2d, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x76, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f,
	0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0f, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x73, 0x5f, 0x76, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x73,
	0x56, 0x12, 0x2f, 0x0a, 0x14, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x11, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x73, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x22, 0x75, 0x0a, 0x2a, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f, 0x67, 0x65, 0x74,
	0x5f, 0x76, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69,
	0x74, 0x65, 0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x11, 0x0a, 0x04, 0x69, 0x73, 0x5f,
	0x76, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x69, 0x73, 0x56, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x3a, 0x0a, 0x1d, 0x64, 0x6f, 0x75,
	0x79, 0x69, 0x6e, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x49, 0x64, 0x22, 0x85, 0x01, 0x0a, 0x0c, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x5f, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x57, 0x0a,
	0x1f, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x76, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x5f, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x3f, 0x0a, 0x24, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e,
	0x5f, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x5f, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x2b, 0x64, 0x6f, 0x75, 0x79, 0x69,
	0x6e, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4a,
	0x0a, 0x30, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42, 0x1c, 0x5a, 0x1a, 0x64, 0x6f,
	0x75, 0x79, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_video_request_request_proto_rawDescOnce sync.Once
	file_video_request_request_proto_rawDescData = file_video_request_request_proto_rawDesc
)

func file_video_request_request_proto_rawDescGZIP() []byte {
	file_video_request_request_proto_rawDescOnce.Do(func() {
		file_video_request_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_video_request_request_proto_rawDescData)
	})
	return file_video_request_request_proto_rawDescData
}

var file_video_request_request_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_video_request_request_proto_goTypes = []interface{}{
	(*DouyinFeedRequest)(nil),                         // 0: request.douyin_feed_request
	(*DouyinPublishActionRequest)(nil),                // 1: request.douyin_publish_action_request
	(*DouyinPublishListRequest)(nil),                  // 2: request.douyin_publish_list_request
	(*DouyinJudgeVideoAuthorRequest)(nil),             // 3: request.douyin_judge_video_author_request
	(*DouyinPushVActiveFavoriteVideoRequest)(nil),     // 4: request.douyin_push_v_active_favorite_video_request
	(*DouyinDeleteVActiveFavoriteVideoRequest)(nil),   // 5: request.douyin_delete_v_active_favorite_video_request
	(*DouyinGetVActiveFavoriteVideoRequest)(nil),      // 6: request.douyin_get_v_active_favorite_video_request
	(*DouyinGetVideoListRequest)(nil),                 // 7: request.douyin_get_video_list_request
	(*Simple_Video)(nil),                              // 8: request.Simple_Video
	(*DouyinPushVInfoInitRequest)(nil),                // 9: request.douyin_push_v_info_init_request
	(*DouyinPushActiveInfoInitRequest)(nil),           // 10: request.douyin_push_active_info_init_request
	(*DouyinGetUserPublishVideoCountRequest)(nil),     // 11: request.douyin_get_user_publish_video_count_request
	(*DouyinGetUserPublishVideoCountListRequest)(nil), // 12: request.douyin_get_user_publish_video_count_list_request
}
var file_video_request_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_video_request_request_proto_init() }
func file_video_request_request_proto_init() {
	if File_video_request_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_video_request_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinFeedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_video_request_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinPublishActionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_video_request_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinPublishListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_video_request_request_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinJudgeVideoAuthorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_video_request_request_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinPushVActiveFavoriteVideoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_video_request_request_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinDeleteVActiveFavoriteVideoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_video_request_request_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinGetVActiveFavoriteVideoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_video_request_request_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinGetVideoListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_video_request_request_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Simple_Video); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_video_request_request_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinPushVInfoInitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_video_request_request_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinPushActiveInfoInitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_video_request_request_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinGetUserPublishVideoCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_video_request_request_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinGetUserPublishVideoCountListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_video_request_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_video_request_request_proto_goTypes,
		DependencyIndexes: file_video_request_request_proto_depIdxs,
		MessageInfos:      file_video_request_request_proto_msgTypes,
	}.Build()
	File_video_request_request_proto = out.File
	file_video_request_request_proto_rawDesc = nil
	file_video_request_request_proto_goTypes = nil
	file_video_request_request_proto_depIdxs = nil
}
