package service

const (
	errorEncryptPassword             = "encrypt password failed"
	errorCreateUser                  = "create user failed"
	errorGenToken                    = "generate token failed"
	errorUserLogin                   = "user login failed"
	errorPassword                    = "password compare failed"
	errorUserLoginCountAdd1          = "user login count redis add 1 failed"
	errorConnectToGRPCServer         = "connect to grpc server failed"
	errorGetFollowFollower           = "get user's follow follower count failed"
	errorGetFollowFollowerList       = "get user's follow follower list count failed"
	errorExeVActiveSet               = "exe if request is V or active from redis set failed"
	errorGetUserInfoFailed           = "get user information failed"
	errorGetFollowInfo               = "get user follow relation from mysql failed"
	errGetVUserInfo                  = "get V User Information from redis failed"
	errGetActiveUserInfo             = "get active User Information from redis failed"
	errorGetVFollowerInfo            = "get v follower information failed"
	errorGetActiveFollowerInfo       = "get active follower information failed"
	errorGetUserInfoListFailed       = "get user information list failed"
	errorGetFollowInfoList           = "get follow information list failed"
	errGetVUserInfoList              = "get v user information list failed"
	errGetActiveUserInfoList         = "get active user information list failed"
	errorGetVFollowerInfoList        = "get v follower information list failed"
	errorGetActiveFollowerInfoList   = "get active follower information list failed"
	errorPushVFollowUserInfo         = "push v follow user information failed"
	errorPushActiveFollowUserInfo    = "push active follow user information failed"
	errorPushVFollowerUserInfo       = "push v follower user information failed"
	errorPushActiveFollowerUserInfo  = "push active follower user information failed"
	errDeleteVFollowUserInfo         = "delete v follow user information failed"
	errDeleteActiveFollowUserInfo    = "delete active follow user information failed"
	errDeleteVFollowerUserInfo       = "delete v follower user information failed"
	errDeleteActiveFollowerUserInfo  = "delete active follower user information failed"
	errorGetVFollowerUserInfo        = "get v follower user information failed"
	errorGetActiveFollowerUserInfo   = "get active follower user information failed"
	errorGetVFollowUserInfo          = "get v follower user information failed"
	errorPushVSet                    = "push v set failed"
	errorPushVString                 = "push v string failed"
	errorPushVFollowFollowerInfoInit = "push v follow follower information init failed"
	errorDeleteActiveAllInfo         = "delete active all information failed"
	errorGetUserPublishVideoCount    = "get user publish video count failed"
	errorGetUserFavoritedCount       = "get user favorited count failed"
	errorRpc                         = "错误的rpc调用输入"
)
