// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: user/request/request.proto

package request

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DouyinUserRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *DouyinUserRegisterRequest) Reset() {
	*x = DouyinUserRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_request_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinUserRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinUserRegisterRequest) ProtoMessage() {}

func (x *DouyinUserRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_request_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinUserRegisterRequest.ProtoReflect.Descriptor instead.
func (*DouyinUserRegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_request_request_proto_rawDescGZIP(), []int{0}
}

func (x *DouyinUserRegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DouyinUserRegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DouyinUserLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *DouyinUserLoginRequest) Reset() {
	*x = DouyinUserLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_request_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinUserLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinUserLoginRequest) ProtoMessage() {}

func (x *DouyinUserLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_request_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinUserLoginRequest.ProtoReflect.Descriptor instead.
func (*DouyinUserLoginRequest) Descriptor() ([]byte, []int) {
	return file_user_request_request_proto_rawDescGZIP(), []int{1}
}

func (x *DouyinUserLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DouyinUserLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DouyinUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LoginUserId int64 `protobuf:"varint,2,opt,name=login_user_id,json=loginUserId,proto3" json:"login_user_id,omitempty"`
}

func (x *DouyinUserRequest) Reset() {
	*x = DouyinUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_request_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinUserRequest) ProtoMessage() {}

func (x *DouyinUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_request_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinUserRequest.ProtoReflect.Descriptor instead.
func (*DouyinUserRequest) Descriptor() ([]byte, []int) {
	return file_user_request_request_proto_rawDescGZIP(), []int{2}
}

func (x *DouyinUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DouyinUserRequest) GetLoginUserId() int64 {
	if x != nil {
		return x.LoginUserId
	}
	return 0
}

type DouyinUserListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      []int64 `protobuf:"varint,1,rep,packed,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LoginUserId int64   `protobuf:"varint,2,opt,name=login_user_id,json=loginUserId,proto3" json:"login_user_id,omitempty"`
}

func (x *DouyinUserListRequest) Reset() {
	*x = DouyinUserListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_request_request_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinUserListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinUserListRequest) ProtoMessage() {}

func (x *DouyinUserListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_request_request_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinUserListRequest.ProtoReflect.Descriptor instead.
func (*DouyinUserListRequest) Descriptor() ([]byte, []int) {
	return file_user_request_request_proto_rawDescGZIP(), []int{3}
}

func (x *DouyinUserListRequest) GetUserId() []int64 {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *DouyinUserListRequest) GetLoginUserId() int64 {
	if x != nil {
		return x.LoginUserId
	}
	return 0
}

type DouyinUserIsInfluencerActiverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DouyinUserIsInfluencerActiverRequest) Reset() {
	*x = DouyinUserIsInfluencerActiverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_request_request_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinUserIsInfluencerActiverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinUserIsInfluencerActiverRequest) ProtoMessage() {}

func (x *DouyinUserIsInfluencerActiverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_request_request_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinUserIsInfluencerActiverRequest.ProtoReflect.Descriptor instead.
func (*DouyinUserIsInfluencerActiverRequest) Descriptor() ([]byte, []int) {
	return file_user_request_request_proto_rawDescGZIP(), []int{4}
}

func (x *DouyinUserIsInfluencerActiverRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DouyinUserVideoCountSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DouyinUserVideoCountSetRequest) Reset() {
	*x = DouyinUserVideoCountSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_request_request_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinUserVideoCountSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinUserVideoCountSetRequest) ProtoMessage() {}

func (x *DouyinUserVideoCountSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_request_request_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinUserVideoCountSetRequest.ProtoReflect.Descriptor instead.
func (*DouyinUserVideoCountSetRequest) Descriptor() ([]byte, []int) {
	return file_user_request_request_proto_rawDescGZIP(), []int{5}
}

func (x *DouyinUserVideoCountSetRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DouyinUserFavoriteVideoCountSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DouyinUserFavoriteVideoCountSetRequest) Reset() {
	*x = DouyinUserFavoriteVideoCountSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_request_request_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinUserFavoriteVideoCountSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinUserFavoriteVideoCountSetRequest) ProtoMessage() {}

func (x *DouyinUserFavoriteVideoCountSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_request_request_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinUserFavoriteVideoCountSetRequest.ProtoReflect.Descriptor instead.
func (*DouyinUserFavoriteVideoCountSetRequest) Descriptor() ([]byte, []int) {
	return file_user_request_request_proto_rawDescGZIP(), []int{6}
}

func (x *DouyinUserFavoriteVideoCountSetRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DouyinPushVSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         int64   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowIdList   []int64 `protobuf:"varint,2,rep,packed,name=follow_id_list,json=followIdList,proto3" json:"follow_id_list,omitempty"`
	FollowerIdList []int64 `protobuf:"varint,3,rep,packed,name=follower_id_list,json=followerIdList,proto3" json:"follower_id_list,omitempty"`
}

func (x *DouyinPushVSetRequest) Reset() {
	*x = DouyinPushVSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_request_request_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinPushVSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinPushVSetRequest) ProtoMessage() {}

func (x *DouyinPushVSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_request_request_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinPushVSetRequest.ProtoReflect.Descriptor instead.
func (*DouyinPushVSetRequest) Descriptor() ([]byte, []int) {
	return file_user_request_request_proto_rawDescGZIP(), []int{7}
}

func (x *DouyinPushVSetRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DouyinPushVSetRequest) GetFollowIdList() []int64 {
	if x != nil {
		return x.FollowIdList
	}
	return nil
}

func (x *DouyinPushVSetRequest) GetFollowerIdList() []int64 {
	if x != nil {
		return x.FollowerIdList
	}
	return nil
}

type DouyinUserFollowCountSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DouyinUserFollowCountSetRequest) Reset() {
	*x = DouyinUserFollowCountSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_request_request_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinUserFollowCountSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinUserFollowCountSetRequest) ProtoMessage() {}

func (x *DouyinUserFollowCountSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_request_request_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinUserFollowCountSetRequest.ProtoReflect.Descriptor instead.
func (*DouyinUserFollowCountSetRequest) Descriptor() ([]byte, []int) {
	return file_user_request_request_proto_rawDescGZIP(), []int{8}
}

func (x *DouyinUserFollowCountSetRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DouyinUserFollowerCountSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DouyinUserFollowerCountSetRequest) Reset() {
	*x = DouyinUserFollowerCountSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_request_request_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinUserFollowerCountSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinUserFollowerCountSetRequest) ProtoMessage() {}

func (x *DouyinUserFollowerCountSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_request_request_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinUserFollowerCountSetRequest.ProtoReflect.Descriptor instead.
func (*DouyinUserFollowerCountSetRequest) Descriptor() ([]byte, []int) {
	return file_user_request_request_proto_rawDescGZIP(), []int{9}
}

func (x *DouyinUserFollowerCountSetRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DouyinVActiveFollowFollowerUserinfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginUserId      int64 `protobuf:"varint,1,opt,name=login_user_id,json=loginUserId,proto3" json:"login_user_id,omitempty"`
	LoginIsV         bool  `protobuf:"varint,2,opt,name=login_is_v,json=loginIsV,proto3" json:"login_is_v,omitempty"`
	LoginIsActive    bool  `protobuf:"varint,3,opt,name=login_is_active,json=loginIsActive,proto3" json:"login_is_active,omitempty"`
	UserId           int64 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsFollowFollower int32 `protobuf:"varint,5,opt,name=is_follow_follower,json=isFollowFollower,proto3" json:"is_follow_follower,omitempty"` //1表示大V或活跃用户关注的用户信息 2表示大V或活跃用户的粉丝信息
	IsV              bool  `protobuf:"varint,6,opt,name=is_v,json=isV,proto3" json:"is_v,omitempty"`
	IsActive         bool  `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (x *DouyinVActiveFollowFollowerUserinfoRequest) Reset() {
	*x = DouyinVActiveFollowFollowerUserinfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_request_request_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinVActiveFollowFollowerUserinfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinVActiveFollowFollowerUserinfoRequest) ProtoMessage() {}

func (x *DouyinVActiveFollowFollowerUserinfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_request_request_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinVActiveFollowFollowerUserinfoRequest.ProtoReflect.Descriptor instead.
func (*DouyinVActiveFollowFollowerUserinfoRequest) Descriptor() ([]byte, []int) {
	return file_user_request_request_proto_rawDescGZIP(), []int{10}
}

func (x *DouyinVActiveFollowFollowerUserinfoRequest) GetLoginUserId() int64 {
	if x != nil {
		return x.LoginUserId
	}
	return 0
}

func (x *DouyinVActiveFollowFollowerUserinfoRequest) GetLoginIsV() bool {
	if x != nil {
		return x.LoginIsV
	}
	return false
}

func (x *DouyinVActiveFollowFollowerUserinfoRequest) GetLoginIsActive() bool {
	if x != nil {
		return x.LoginIsActive
	}
	return false
}

func (x *DouyinVActiveFollowFollowerUserinfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DouyinVActiveFollowFollowerUserinfoRequest) GetIsFollowFollower() int32 {
	if x != nil {
		return x.IsFollowFollower
	}
	return 0
}

func (x *DouyinVActiveFollowFollowerUserinfoRequest) GetIsV() bool {
	if x != nil {
		return x.IsV
	}
	return false
}

func (x *DouyinVActiveFollowFollowerUserinfoRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type DouyinDeleteVActiveFollowFollowerUserinfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginUserId      int64 `protobuf:"varint,1,opt,name=login_user_id,json=loginUserId,proto3" json:"login_user_id,omitempty"`
	LoginIsV         bool  `protobuf:"varint,2,opt,name=login_is_v,json=loginIsV,proto3" json:"login_is_v,omitempty"`
	LoginIsActive    bool  `protobuf:"varint,3,opt,name=login_is_active,json=loginIsActive,proto3" json:"login_is_active,omitempty"`
	UserId           int64 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsFollowFollower int32 `protobuf:"varint,5,opt,name=is_follow_follower,json=isFollowFollower,proto3" json:"is_follow_follower,omitempty"` //1表示大V或活跃用户关注的用户信息 2表示大V或活跃用户的粉丝信息
	IsV              bool  `protobuf:"varint,6,opt,name=is_v,json=isV,proto3" json:"is_v,omitempty"`
	IsActive         bool  `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (x *DouyinDeleteVActiveFollowFollowerUserinfoRequest) Reset() {
	*x = DouyinDeleteVActiveFollowFollowerUserinfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_request_request_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinDeleteVActiveFollowFollowerUserinfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinDeleteVActiveFollowFollowerUserinfoRequest) ProtoMessage() {}

func (x *DouyinDeleteVActiveFollowFollowerUserinfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_request_request_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinDeleteVActiveFollowFollowerUserinfoRequest.ProtoReflect.Descriptor instead.
func (*DouyinDeleteVActiveFollowFollowerUserinfoRequest) Descriptor() ([]byte, []int) {
	return file_user_request_request_proto_rawDescGZIP(), []int{11}
}

func (x *DouyinDeleteVActiveFollowFollowerUserinfoRequest) GetLoginUserId() int64 {
	if x != nil {
		return x.LoginUserId
	}
	return 0
}

func (x *DouyinDeleteVActiveFollowFollowerUserinfoRequest) GetLoginIsV() bool {
	if x != nil {
		return x.LoginIsV
	}
	return false
}

func (x *DouyinDeleteVActiveFollowFollowerUserinfoRequest) GetLoginIsActive() bool {
	if x != nil {
		return x.LoginIsActive
	}
	return false
}

func (x *DouyinDeleteVActiveFollowFollowerUserinfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DouyinDeleteVActiveFollowFollowerUserinfoRequest) GetIsFollowFollower() int32 {
	if x != nil {
		return x.IsFollowFollower
	}
	return 0
}

func (x *DouyinDeleteVActiveFollowFollowerUserinfoRequest) GetIsV() bool {
	if x != nil {
		return x.IsV
	}
	return false
}

func (x *DouyinDeleteVActiveFollowFollowerUserinfoRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type DouyinGetVActiveFollowFollowerUserinfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginUserId      int64 `protobuf:"varint,1,opt,name=login_user_id,json=loginUserId,proto3" json:"login_user_id,omitempty"`
	UserId           int64 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsFollowFollower int32 `protobuf:"varint,5,opt,name=is_follow_follower,json=isFollowFollower,proto3" json:"is_follow_follower,omitempty"` //1表示follow 2表示follower
	IsV              bool  `protobuf:"varint,6,opt,name=is_v,json=isV,proto3" json:"is_v,omitempty"`
	IsActive         bool  `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (x *DouyinGetVActiveFollowFollowerUserinfoRequest) Reset() {
	*x = DouyinGetVActiveFollowFollowerUserinfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_request_request_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DouyinGetVActiveFollowFollowerUserinfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DouyinGetVActiveFollowFollowerUserinfoRequest) ProtoMessage() {}

func (x *DouyinGetVActiveFollowFollowerUserinfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_request_request_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DouyinGetVActiveFollowFollowerUserinfoRequest.ProtoReflect.Descriptor instead.
func (*DouyinGetVActiveFollowFollowerUserinfoRequest) Descriptor() ([]byte, []int) {
	return file_user_request_request_proto_rawDescGZIP(), []int{12}
}

func (x *DouyinGetVActiveFollowFollowerUserinfoRequest) GetLoginUserId() int64 {
	if x != nil {
		return x.LoginUserId
	}
	return 0
}

func (x *DouyinGetVActiveFollowFollowerUserinfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DouyinGetVActiveFollowFollowerUserinfoRequest) GetIsFollowFollower() int32 {
	if x != nil {
		return x.IsFollowFollower
	}
	return 0
}

func (x *DouyinGetVActiveFollowFollowerUserinfoRequest) GetIsV() bool {
	if x != nil {
		return x.IsV
	}
	return false
}

func (x *DouyinGetVActiveFollowFollowerUserinfoRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type TestIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *TestIn) Reset() {
	*x = TestIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_request_request_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestIn) ProtoMessage() {}

func (x *TestIn) ProtoReflect() protoreflect.Message {
	mi := &file_user_request_request_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestIn.ProtoReflect.Descriptor instead.
func (*TestIn) Descriptor() ([]byte, []int) {
	return file_user_request_request_proto_rawDescGZIP(), []int{13}
}

func (x *TestIn) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_request_request_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_user_request_request_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_user_request_request_proto_rawDescGZIP(), []int{14}
}

var File_user_request_request_proto protoreflect.FileDescriptor

var file_user_request_request_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x56, 0x0a, 0x1c, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x53, 0x0a,
	0x19, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0x52, 0x0a, 0x13, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x18, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x44, 0x0a, 0x29, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6c, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x23, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x2c, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x84,
	0x01, 0x0a, 0x19, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x76,
	0x5f, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f,
	0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0c, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x49,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x3f, 0x0a, 0x24, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x26, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x93, 0x02, 0x0a, 0x30, 0x64, 0x6f,
	0x75, 0x79, 0x69, 0x6e, 0x5f, 0x76, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22,
	0x0a, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x73, 0x5f, 0x76,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x73, 0x56,
	0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x49, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x2c, 0x0a, 0x12, 0x69, 0x73, 0x5f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x69,
	0x73, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x12,
	0x11, 0x0a, 0x04, 0x69, 0x73, 0x5f, 0x76, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x69,
	0x73, 0x56, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22,
	0x9a, 0x02, 0x0a, 0x37, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x5f, 0x76, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x5f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x69,
	0x6e, 0x66, 0x6f, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x73, 0x5f, 0x76, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x73, 0x56, 0x12, 0x26, 0x0a,
	0x0f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x73, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2c,
	0x0a, 0x12, 0x69, 0x73, 0x5f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x66, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x69, 0x73, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x11, 0x0a, 0x04,
	0x69, 0x73, 0x5f, 0x76, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x69, 0x73, 0x56, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0xd1, 0x01, 0x0a,
	0x34, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x76, 0x5f, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x5f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x66, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x69, 0x73, 0x5f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f,
	0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10,
	0x69, 0x73, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72,
	0x12, 0x11, 0x0a, 0x04, 0x69, 0x73, 0x5f, 0x76, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03,
	0x69, 0x73, 0x56, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x22, 0x1f, 0x0a, 0x07, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x07, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x1b, 0x5a, 0x19, 0x64, 0x6f,
	0x75, 0x79, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_request_request_proto_rawDescOnce sync.Once
	file_user_request_request_proto_rawDescData = file_user_request_request_proto_rawDesc
)

func file_user_request_request_proto_rawDescGZIP() []byte {
	file_user_request_request_proto_rawDescOnce.Do(func() {
		file_user_request_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_request_request_proto_rawDescData)
	})
	return file_user_request_request_proto_rawDescData
}

var file_user_request_request_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_user_request_request_proto_goTypes = []interface{}{
	(*DouyinUserRegisterRequest)(nil),                        // 0: request.douyin_user_register_request
	(*DouyinUserLoginRequest)(nil),                           // 1: request.douyin_user_login_request
	(*DouyinUserRequest)(nil),                                // 2: request.douyin_user_request
	(*DouyinUserListRequest)(nil),                            // 3: request.douyin_user_list_request
	(*DouyinUserIsInfluencerActiverRequest)(nil),             // 4: request.douyin_user_is_influencer_activer_request
	(*DouyinUserVideoCountSetRequest)(nil),                   // 5: request.douyin_user_video_count_set_request
	(*DouyinUserFavoriteVideoCountSetRequest)(nil),           // 6: request.douyin_user_favorite_video_count_set_request
	(*DouyinPushVSetRequest)(nil),                            // 7: request.douyin_push_v_set_request
	(*DouyinUserFollowCountSetRequest)(nil),                  // 8: request.douyin_user_follow_count_set_request
	(*DouyinUserFollowerCountSetRequest)(nil),                // 9: request.douyin_user_follower_count_set_request
	(*DouyinVActiveFollowFollowerUserinfoRequest)(nil),       // 10: request.douyin_v_active_follow_follower_userinfo_request
	(*DouyinDeleteVActiveFollowFollowerUserinfoRequest)(nil), // 11: request.douyin_delete_v_active_follow_follower_userinfo_request
	(*DouyinGetVActiveFollowFollowerUserinfoRequest)(nil),    // 12: request.douyin_get_v_active_follow_follower_userinfo_request
	(*TestIn)(nil), // 13: request.test_in
	(*Empty)(nil),  // 14: request.empty
}
var file_user_request_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_request_request_proto_init() }
func file_user_request_request_proto_init() {
	if File_user_request_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_request_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinUserRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_request_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinUserLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_request_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_request_request_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinUserListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_request_request_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinUserIsInfluencerActiverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_request_request_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinUserVideoCountSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_request_request_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinUserFavoriteVideoCountSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_request_request_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinPushVSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_request_request_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinUserFollowCountSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_request_request_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinUserFollowerCountSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_request_request_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinVActiveFollowFollowerUserinfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_request_request_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinDeleteVActiveFollowFollowerUserinfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_request_request_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DouyinGetVActiveFollowFollowerUserinfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_request_request_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_request_request_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_request_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_request_request_proto_goTypes,
		DependencyIndexes: file_user_request_request_proto_depIdxs,
		MessageInfos:      file_user_request_request_proto_msgTypes,
	}.Build()
	File_user_request_request_proto = out.File
	file_user_request_request_proto_rawDesc = nil
	file_user_request_request_proto_goTypes = nil
	file_user_request_request_proto_depIdxs = nil
}
